### ISSUE TITLE
Bug with using nested erb

### ISSUE THREAD

**Issue by frmsaul** [ruby/erb#45]
When I run:
```ruby
ERB.new("1. <%= ERB.new('2').result binding %>. 3").result binding
```

The output is: 
```2. 3```

While the expected output is:
```1. 2. 3```

Seems like the nested erb is deleting everything before it in the template. Has anyone seen this before? What is the recommended way of nesting erbs? Is it possible?

**Comment by k0kubun** [comment]
It should be something like `ERB.new("1. <%= ERB.new('2', eoutvar: '_erbout2').result binding %>. 3").result binding`. Template engines rely on a local variable for buffer concatenation, and there's no way that it could work when multiple engines share the same variable by passing `binding`, and it seems fair that it happens.

**Comment by frmsaul** [comment]
This worked for me! Thank you. 

If i run ERB.new(x).result in two different threads at the same time do i also need to pass `eoutvar:`?

**Comment by k0kubun** [comment]
No, it should be fine.
